/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface ImageBackgroundProps {
  src: string;
  alt: string;
}

const ImageBackground: React.FC<ImageBackgroundProps> = ({ src, alt }) => {
  return (
    <div className="relative w-full h-screen">
      <img
        src={src}
        alt={alt}
        className="absolute inset-0 w-full h-full object-cover"
        loading="lazy"
      />
    </div>
  );
};

export default ImageBackground;
