/**
 * This code was generated by Builder.io.
 */
import React from "react";
import NightOfSeptember from "./NightOfSeptember";

const App: React.FC = () => {
  return (
    <main>
      <NightOfSeptember title="Do You Remember the 21st Night of September?" />
    </main>
  );
};

export default App;