/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface EarthWindFireProps {
  imageUrl: string;
  altText: string;
}

const EarthWindFire: React.FC<EarthWindFireProps> = ({ imageUrl, altText }) => {
  return (
    <section className="box-border flex relative flex-col grow shrink-0 self-stretch p-5 mx-auto w-full max-w-[1200px] min-h-[100px]">
      <img
        loading="lazy"
        alt={altText}
        src={imageUrl}
        className="box-border object-cover overflow-hidden shrink-0 mt-5 w-full aspect-[2.33] max-w-[1184px] min-h-[20px] min-w-[20px]"
      />
    </section>
  );
};

export default EarthWindFire;