/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface InfoCardProps {
  title: string;
  description: string;
  imageSrc?: string;
}

const InfoCard: React.FC<InfoCardProps> = ({
  title,
  description,
  imageSrc,
}) => {
  return (
    <div className="box-border flex relative flex-col shrink-0 justify-center pl-5 text-black max-w-[50%] max-sm:items-center max-sm:max-w-[300px]">
      <h2 className="box-border relative shrink-0 mb-2.5 h-auto font-semibold text-left text-black">
        {title}
      </h2>
      <p className="box-border relative shrink-0 h-auto text-xs text-left text-black max-sm:text-center">
        {description}
      </p>
      {imageSrc && (
        <img
          loading="lazy"
          sizes="(max-width: 998px) 11vw, 8vw"
          src={imageSrc}
          className="box-border object-contain overflow-hidden shrink-0 mt-5 ml-auto w-full aspect-[2.88] max-w-[102px] min-h-[20px] min-w-[20px] max-md:flex max-sm:hidden"
          alt="Info card illustration"
        />
      )}
    </div>
  );
};

export default InfoCard;
