/**
 * This code was generated by Builder.io.
 */
import React from "react";
import EarthWindFire from "./EarthWindFire";

const MainContainer: React.FC = () => {
  return (
    <main className="box-border flex relative flex-col shrink-0 p-5 min-h-[100px]" style={{ maxWidth: 1200 }}>
      <EarthWindFire
        imageUrl="https://cdn.builder.io/api/v1/image/assets%2F8fe1ce70d69547aaa2993cd03f7abc7b%2F446a320b26744f5d8a037c27c3acc64d"
        altText="earth wind fire"
      />
    </main>
  );
};

export default MainContainer;