/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface MyComponentProps {
  // Add any props here if needed
}

const MyComponent: React.FC<MyComponentProps> = () => {
  return (
    <main className="box-border flex relative flex-col shrink-0 mt-5">
      <section className="flex gap-5 max-md:flex-col">
        <article className="flex flex-col w-full max-md:ml-0 max-md:w-full" />
      </section>
    </main>
  );
};

export default MyComponent;