/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface NightOfSeptemberProps {
  title: string;
}

const NightOfSeptember: React.FC<NightOfSeptemberProps> = ({ title }) => {
  return (
    <header className="box-border relative shrink-0 mt-5 w-full h-auto max-w-[974px]">
      <h1 className="text-3xl font-semibold text-center text-black">{title}</h1>
    </header>
  );
};

export default NightOfSeptember;