/**
 * This code was generated by Builder.io.
 */
import React from "react";
import ImageBackground from "../ImageBackground/ImageBackground";

const App: React.FC = () => {
  return (
    <main className="min-h-screen">
      <ImageBackground
        src="https://cdn.builder.io/api/v1/image/assets%2F8fe1ce70d69547aaa2993cd03f7abc7b%2F4b5a551ad1674c6d93e217c34ef9f6df"
        alt="Background image"
      />
    </main>
  );
};

export default App;
