/**
 * This code was generated by Builder.io.
 */
import React from "react";

const BackgroundImage: React.FC = () => {
  return (
    <img
      loading="lazy"
      src="https://cdn.builder.io/api/v1/image/assets%2F8fe1ce70d69547aaa2993cd03f7abc7b%2F4b5a551ad1674c6d93e217c34ef9f6df"
      className="box-border object-cover overflow-hidden absolute shrink-0 self-center my-auto w-full h-screen aspect-[2.33] min-h-[20px] min-w-[20px] z-[1] max-md:grow max-md:h-screen"
      alt="Background image of the 21st night of September"
    />
  );
};

export default BackgroundImage;
