/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Header: React.FC = () => {
  return (
    <header className="box-border flex relative flex-col shrink-0 items-center px-5">
      <div className="box-border flex relative flex-row shrink-0 gap-7 justify-center">
        <img
          loading="lazy"
          sizes="(max-width: 638px) 8vw, (max-width: 998px) 6vw, 4vw"
          src="https://cdn.builder.io/api/v1/image/assets%2FYJIGb4i01jvw0SRdL5Bt%2F7bca7936d0a54d568dc5da34f4aaa5af?width=50"
          alt=""
          className="box-border object-contain overflow-hidden shrink-0 w-full aspect-square max-w-[50px] min-h-[20px] min-w-[20px]"
        />
        <div className="box-border relative shrink-0 self-center w-auto h-auto text-3xl font-light text-black">
          <p>+</p>
        </div>
        <img
          loading="lazy"
          sizes="(max-width: 638px) 7vw, (max-width: 998px) 4vw, 3vw"
          src="https://cdn.builder.io/api/v1/image/assets%2F8d9ee72a33344b4b867918b442ebd0af%2F674df6ccd3c94f29bf67d9a8e5b00e08?width=39"
          alt=""
          className="box-border object-contain overflow-hidden shrink-0 w-full aspect-[0.88] max-w-[39px] min-h-[20px] min-w-[20px]"
        />
      </div>
      <h1 className="box-border relative shrink-0 mt-5 w-full h-auto text-3xl font-semibold text-center text-black max-w-[974px]">
        Do You Remember the 21st Night of September?
      </h1>
    </header>
  );
};

export default Header;
