  /**
 * This code was generated by Builder.io.
 */
import React from 'react';

const lyrics = [
  "Do you remember",
  "The twenty-first night of September?",
  "Love was changin the minds of pretenders",
  "While chasin the clouds away",
  "Our hearts were ringin",
  "In the key that our souls were singin",
  "As we danced in the night",
  "In the key that our souls were singin",
  "As we danced in the night, remember",
  "How the stars stole the night away, oh yeah",
  "[Chorus]",
  "Hey, hey, hey",
  "Ba-dee-ya",
  "Say, do you remember?",
  "Ba-dee-ya",
  "Dancin' in September",
  "Ba-dee-ya",
  "Never was a cloudy day",
  "[Post-Chorus]",
  "Ba-du, ba-du, ba-du, ba-du",
  "Ba-du, ba-du, ba-du, ba-du",
  "Ba-du, ba-du, ba-du-da",
  "Ba-du, yeah",
  "[Verse 2]",
  "My thoughts are with you",
  "Holdin hands with your heart to see you",
  "Only blue talk and love, remember",
  "How we knew love was here to stay",
  "Now December",
  "Found a love we shared in September",
  "Only blue talk and love, remember",
  "True love we share today"]
