/**
 * This code was generated by Builder.io.
 */
import React from "react";
import LyricsContent from "./LyricsContent";

const LyricsSection: React.FC = () => {
  return (
    <main
      className="box-border flex relative flex-col shrink-0 p-5 min-h-[100px]"
      style={{ maxWidth: 1200 }}
    >
      <section className="box-border flex relative flex-col grow shrink-0 self-stretch p-5 mx-auto w-full max-w-[1200px] min-h-[100px]">
        <div className="box-border flex relative flex-col shrink-0 mt-5">
          <div className="flex gap-5 max-md:flex-col">
            <div className="flex flex-col w-[67%] max-md:ml-0 max-md:w-full">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets%2F8fe1ce70d69547aaa2993cd03f7abc7b%2F9539dec94fed455485de4a5413c1bc41"
                alt="September night scene"
                className="box-border object-cover overflow-hidden shrink-0 mt-5 w-full aspect-[1.6] min-h-[20px] min-w-[20px]"
              />
            </div>
            <LyricsContent />
          </div>
        </div>
      </section>
    </main>
  );
};

export default LyricsSection;
