/**
 * This code was generated by Builder.io.
 */
import React from "react";

const MainContent: React.FC = () => {
  return (
    <main className="box-border flex relative flex-col shrink-0 self-stretch px-5 h-screen bg-white bg-center bg-no-repeat bg-cover grow-0 max-md:h-screen max-md:grow-0">
      <section className="box-border flex relative flex-col grow shrink-0 self-stretch px-5 mx-auto w-full h-screen bg-white bg-center bg-no-repeat bg-cover max-w-[1440px] max-md:h-screen max-md:grow-0">
        <div className="flex flex-col justify-start px-3 mx-auto mt-auto mb-16 w-full grow-0 z-[999] max-md:flex max-md:flex-col max-md:items-center max-md:m-auto max-md:h-auto max-md:grow-0 max-sm:flex max-sm:flex-col max-sm:mx-auto max-sm:mt-auto">
          <h1 className="self-stretch w-full max-w-full text-xl font-bold text-center text-white leading-[120%] max-md:self-stretch max-md:w-auto max-md:text-6xl max-md:text-center max-sm:text-6xl max-sm:leading-[100%]">
            <span className="bg-black bg-opacity-50">
              Do You Remember the 21st Night of September?
            </span>
          </h1>
          <div className="flex flex-row gap-4 self-center mx-auto mt-9 w-full max-w-[444px] max-md:justify-center max-md:items-center max-md:self-stretch max-md:mx-auto max-md:w-full">
            <a
              href="/lyrics"
              className="box-border relative grow shrink-0 p-6 my-auto w-auto text-center text-black bg-white rounded border border-white border-solid appearance-none cursor-pointer"
            >
              Yes
            </a>
            <a
              href="https://www.youtube.com/watch?v=131OjWrdYwc"
              className="box-border relative grow shrink-0 p-6 m-auto w-auto text-center rounded border-2 border-solid appearance-none cursor-pointer bg-black bg-opacity-40 border-[black] text-[white]"
              target="_blank"
              rel="noopener noreferrer"
            >
              No
            </a>
          </div>
        </div>
      </section>
    </main>
  );
};

export default MainContent;
