/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "./Header";
import LyricsSection from "./LyricsSection";

const SeptemberNight: React.FC = () => {
  return (
    <>
      <Header />
      <LyricsSection />
    </>
  );
};

export default SeptemberNight;
